AWSTemplateFormatVersion: "2010-09-09"
Description: CSYE6225 Network Infrastructure
Parameters:
  VpcCidrBlock:
    Description: "CIDR block for VPC"
    Type: String
    Default: "10.0.0.0/16"
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      InstanceTenancy: "default"
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
Outputs:
  VpcId:
    Description: "The VPC ID"
    Value: !Ref myVPC
  SubnetId:
    Description: "The Subnet ID"
    Value: !Ref mySubnet
